name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Compile
        run: "pnpm build"

      - name: Test with QuickJS
        uses: refracturemedia/quickjs-gh-action/@v0.1.1
        with:
          mainFile: dist/bundle.js